services:
  client:
    build: ./client
    ports:
      - 8080:3000
    volumes:
      - ./client/src:/app/src
  server:
    build: ./server
    ports:
      - 5000:5000
      - 4000:4000
    command: yarn start:dev
    volumes:
      - ./server/src:/server/src
    environment:
      - DOTENVENC_KEY=${DOTENVENC_KEY}
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
