services:
    client:
        build: ./client
        command: sh -c "REACT_APP_GATEWAY_PORT=${GATEWAY_PORT} npm run build"
        volumes:
            - web-client-build:/app/build
    server:
        build: ./server
        command: sh -c "DOTENVENC_KEY=${DOTENVENC_KEY} SERVER_STAGE=${SERVER_STAGE} npm run start:prod"
    mongodb:
        image: mongo:4.4.9
    nginx:
        image: nginx:1.21.3
        depends_on:
            - server
            - client
        restart: unless-stopped
        ports:
            - ${GATEWAY_PORT}:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - web-client-build:/web-client-build
            - ./logs:/var/log/nginx
volumes:
    web-client-build:
